name: Code Coverage Summary Report
description: Creates a coverage summary based on lcov report
author: Dmitriy Rodin
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  pr-number:
    description: Number of the Pull Request
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  filter-changed-files:
    description: Set to true to only comment with coverage on files changed in this commit
    required: false
    default: false
  working-directory:
    description: Set working directory if project is not in root folder
    required: false
    default: "./"
  title:
    description: Title to add to the comment
    required: false
runs:
  using: node12
  main: dist/main.js
